name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2023-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Spotless Check
        run: ./gradlew spotlessCheck
      - name: Spotless Apply
        run: ./gradlew :spotlessAppl
      - name: Build
        run: ./gradlew build
